// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOwvX9jzRMa74cuiWZhCk_Ibq_Z0AOEYA',
    appId: '1:727483474692:web:a561ac22026d5f9fcee651',
    messagingSenderId: '727483474692',
    projectId: 'deliver-eats-889b3',
    authDomain: 'deliver-eats-889b3.firebaseapp.com',
    storageBucket: 'deliver-eats-889b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiDJ7ZuM2G1ZJnZX7qPRKVk3jTaHhzckA',
    appId: '1:727483474692:android:139516ae83ffb257cee651',
    messagingSenderId: '727483474692',
    projectId: 'deliver-eats-889b3',
    storageBucket: 'deliver-eats-889b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKXxacUzDdEuuHed0my3Cj1ftKKC2r58',
    appId: '1:727483474692:ios:7ec9b644cdac8825cee651',
    messagingSenderId: '727483474692',
    projectId: 'deliver-eats-889b3',
    storageBucket: 'deliver-eats-889b3.appspot.com',
    iosClientId: '727483474692-k272fsrb0r5kqk4h1pbc55tc7u65rli3.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverEats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKXxacUzDdEuuHed0my3Cj1ftKKC2r58',
    appId: '1:727483474692:ios:7ec9b644cdac8825cee651',
    messagingSenderId: '727483474692',
    projectId: 'deliver-eats-889b3',
    storageBucket: 'deliver-eats-889b3.appspot.com',
    iosClientId: '727483474692-k272fsrb0r5kqk4h1pbc55tc7u65rli3.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverEats',
  );
}
